spring:
  application:
    name: CardCollectionService
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO

app:
  imports:
    ygo:
      enabled: true
      address: https://db.ygoprodeck.com/api/v7/cardinfo.php

